### ISSUE TITLE
Associations

### ISSUE THREAD

**Issue by adalbertorsilva** [felixfbecker/sequelize-decorators#55] opened 2018-03-05 20:33 UTC
Hi Felix !

Is it possible to make model associations ( one to many, many to many, etc... ) using sequelize decorators and ES6 classes ? If true, how can i make it ?

**Comment by felixfbecker** [comment] 2018-03-05 20:39
Duplicate of https://github.com/felixfbecker/sequelize-decorators/issues/28

**Closed by felixfbecker** 2018-03-05 20:39 UTC
